In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)


[5 7 9]


In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a * b)


[ 4 10 18]


In [3]:
import numpy as np

a = np.array([1, 2, 3])

print(np.sqrt(a))


[1.         1.41421356 1.73205081]


In [4]:
import numpy as np

a = np.array([1, 2, 3])

print(np.sum(a))


6


In [5]:
import numpy as np

a = np.array([1, 2, 3])

print(np.mean(a))


2.0


In [6]:
import numpy as np

a = np.array([1, 2, 3])

print(np.max(a))


3


In [7]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(np.min(a))


1


In [8]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(np.var(a))


2.0


In [9]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(np.std(a))


1.4142135623730951


In [10]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(np.median(a))


3.0


In [11]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)


[5 7 9]
