In [1]:
import numpy as np
a=np.array([1,2,3,4,])
print(a)

[1 2 3 4]


In [2]:
import numpy as np
a=np.zeros((2,3))
print(a)


[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np
a=np.ones((3,2))
print(a)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
import numpy as np
a=np.full((2,2),7)
print(a)

[[7 7]
 [7 7]]


In [5]:
import numpy as np
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [9]:
import numpy as np

a = np.linspace(1, 10, 5)
print(a)


[ 1.    3.25  5.5   7.75 10.  ]


In [8]:
import numpy as np
a =np.arange(1,7)
b=a.reshape(2,3)
print(b)


[[1 2 3]
 [4 5 6]]


In [10]:
import numpy as np
a=np.array([[1,2],
            [3,4]])
print(a.flatten())

[1 2 3 4]


In [12]:
import numpy as np
a=np.array([[1,2],
            [3,4]])

print( a.T)          

[[1 3]
 [2 4]]


In [16]:
import numpy as np 
a=np.array([[1,2,3],
            [4,5,6]])
print(a.ndim)

2


In [17]:
import numpy as np 
a=np.array([[1,2,3],
            [4,5,6]])
print(a.shape)

(2, 3)


In [19]:
import numpy as np 
a=np.array([[1,2,3],
            [4,5,6]])
print(a.size)

6


In [20]:
import numpy as np 
a=np.array([[1,2,3],
            [4,5,6]])
print(a.dtype)

int64


In [21]:
import numpy as np 
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [22]:
import numpy as np 
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a*b)

[ 4 10 18]


In [24]:
import numpy as np 
a=np.array([1,2,3])
print(np.sqrt(a))

[1.         1.41421356 1.73205081]


In [25]:
import numpy as np 
a=np.array([1,2,3])
print(np.sum(a))

6


In [26]:
import numpy as np 
a=np.array([1,2,3])
print(np.mean(a))

2.0


In [27]:
import numpy as np 
a=np.array([1,2,3])
print(np.max(a))

3


In [28]:
import numpy as np
a=np.array([1,2,3,4,5])
print(np.min(a))

1


In [29]:
import numpy as np
a=np.array([1,2,3,4,5])
print(np.var(a))

2.0


In [30]:
import numpy as np
a=np.array([1,2,3,4,5])
print(np.std(a))

1.4142135623730951


In [31]:
import numpy as np
a=np.array([1,2,3,4,5])
print(np.median(a))

3.0


In [32]:
import numpy as np
print(np.random.rand(2,2))

[[0.98855343 0.1807867 ]
 [0.83016456 0.08386748]]


In [34]:
import numpy as np
print(np.random.randint(1,10,5))

[5 6 3 8 3]


In [35]:
import numpy as np
a=np.array([1,2,3,4])
print(np.any(a>3))

True


In [36]:
import numpy as np
a=np.array([1,2,3,4])
print(np.all(a>0))

True


In [37]:
import numpy as np
a=np.array([4,1,3,2])
print(np.sort(a))

[1 2 3 4]


In [38]:
import numpy as np
a=np.array([4,1,3,2])
print(np.argmax(a))

0


In [39]:
import numpy as np
a=np.array([4,1,3,2])
print(np.argmin(a))

1
