In [1]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [2]:
import numpy as np
zeroes_array=np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


In [3]:
import numpy as np
ones_array=np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
import numpy as np
filled_array=np.full((2,2),7)
print(filled_array)

[[7 7]
 [7 7]]


In [6]:
import numpy as np
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [8]:
import numpy as np
identity_martix=np.eye(4)
print(identity_martix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
